### ISSUE TITLE
Random crashes...

### ISSUE THREAD

**Issue by l3gendarii** [Yegiyan/Him#1]
For whatever reason my game just crashes sometimes when he starts hunting. One possible cause might be the physics mod. After I turned it off it went well for a while but after some time crashed due to his hunting again.
Here's the log:

[22:21:32] [Server thread/INFO]:
 Time until next stalking: 136 seconds
[22:21:32] [Server thread/INFO]:
 Time until next haunting: 2 seconds
[22:21:32] [Server thread/INFO]:
 Time until next griefing: 72 seconds
[22:21:34] [Server thread/ERROR]:
 Encountered an unexpected exception
net.minecraft.class_148: Exception ticking world
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:952) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:845) ~[client-intermediary.jar:?]
	at net.minecraft.class_1132.method_3748(class_1132.java:110) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:683) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270) ~[client-intermediary.jar:?]
	at java.lang.Thread.run(Unknown Source) ~[?:?]
Caused by: java.lang.NoClassDefFoundError: net/minecraft/class_2368
	at com.him.events.HimHaunt.manipulateBlocks(HimHaunt.java:216) ~[him-1.20.1-1.1.2.jar:?]
	at com.him.events.HimHaunt.haunt(HimHaunt.java:51) ~[him-1.20.1-1.1.2.jar:?]
	at com.him.Him.lambda$updateHim$1(Him.java:147) ~[him-1.20.1-1.1.2.jar:?]
	at net.fabricmc.fabric.api.event.lifecycle.v1.ServerTickEvents.lambda$static$6(ServerTickEvents.java:63) ~[fabric-lifecycle-events-v1-2.3.0+a67ffb5d4f-df781ed0de5bc62e.jar:?]
	at net.minecraft.class_3218.handler$bkc000$fabric-lifecycle-events-v1$endWorldTick(class_3218.java:5274) ~[client-intermediary.jar:?]
	at net.minecraft.class_3218.method_18765(class_3218.java:410) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:948) ~[client-intermediary.jar:?]
	... 5 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.class_2368
	at jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source) ~[?:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226) ~[fabric-loader-0.15.6.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.15.6.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
	at com.him.events.HimHaunt.manipulateBlocks(HimHaunt.java:216) ~[him-1.20.1-1.1.2.jar:?]
	at com.him.events.HimHaunt.haunt(HimHaunt.java:51) ~[him-1.20.1-1.1.2.jar:?]
	at com.him.Him.lambda$updateHim$1(Him.java:147) ~[him-1.20.1-1.1.2.jar:?]
	at net.fabricmc.fabric.api.event.lifecycle.v1.ServerTickEvents.lambda$static$6(ServerTickEvents.java:63) ~[fabric-lifecycle-events-v1-2.3.0+a67ffb5d4f-df781ed0de5bc62e.jar:?]
	at net.minecraft.class_3218.handler$bkc000$fabric-lifecycle-events-v1$endWorldTick(class_3218.java:5274) ~[client-intermediary.jar:?]
	at net.minecraft.class_3218.method_18765(class_3218.java:410) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:948) ~[client-intermediary.jar:?]
	... 5 more
[22:21:34] [Server thread/ERROR]:
 This crash report has been saved to: C:\Users\{COMPUTER_USERNAME}\AppData\Roaming\com.modrinth.theseus\profiles\modz\crash-reports\crash-2024-02-14_22.21.34-server.txt
[22:21:34] [Server thread/INFO]:
 Stopping server
[22:21:34] [Server thread/INFO]:
 Saving players

**Comment by Yegiyan** [comment]
Thanks for the report, what version of Minecraft are you playing on?

**Comment by Ihatetallgrass** [comment]
I am also getting the same crash report after. My version is 1.20.4 and my mods are
Bobby + nvidium
sodium
cloth config api
fabric api
logical zoom

[14:39:53] [Server thread/ERROR]:
 Encountered an unexpected exception
net.minecraft.class_148: Exception ticking world
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:952) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:845) ~[client-intermediary.jar:?]
	at net.minecraft.class_1132.method_3748(class_1132.java:110) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:683) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270) ~[client-intermediary.jar:?]
	at java.lang.Thread.run(Unknown Source) ~[?:?]
Caused by: java.lang.NoClassDefFoundError: net/minecraft/class_2368
	at com.him.events.HimHaunt.manipulateBlocks(HimHaunt.java:216) ~[him-1.20.1-1.1.2.jar:?]
	at com.him.events.HimHaunt.haunt(HimHaunt.java:51) ~[him-1.20.1-1.1.2.jar:?]
	at com.him.Him.lambda$updateHim$1(Him.java:147) ~[him-1.20.1-1.1.2.jar:?]
	at net.fabricmc.fabric.api.event.lifecycle.v1.ServerTickEvents.lambda$static$6(ServerTickEvents.java:63) ~[fabric-lifecycle-events-v1-2.3.0+a67ffb5d4f-df781ed0de5bc62e.jar:?]
	at net.minecraft.class_3218.handler$zfm000$fabric-lifecycle-events-v1$endWorldTick(class_3218.java:2774) ~[client-intermediary.jar:?]
	at net.minecraft.class_3218.method_18765(class_3218.java:410) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:948) ~[client-intermediary.jar:?]
	... 5 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.class_2368
	at jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source) ~[?:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226) ~[fabric-loader-0.15.6.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.15.6.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
	at com.him.events.HimHaunt.manipulateBlocks(HimHaunt.java:216) ~[him-1.20.1-1.1.2.jar:?]
	at com.him.events.HimHaunt.haunt(HimHaunt.java:51) ~[him-1.20.1-1.1.2.jar:?]
	at com.him.Him.lambda$updateHim$1(Him.java:147) ~[him-1.20.1-1.1.2.jar:?]
	at net.fabricmc.fabric.api.event.lifecycle.v1.ServerTickEvents.lambda$static$6(ServerTickEvents.java:63) ~[fabric-lifecycle-events-v1-2.3.0+a67ffb5d4f-df781ed0de5bc62e.jar:?]
	at net.minecraft.class_3218.handler$zfm000$fabric-lifecycle-events-v1$endWorldTick(class_3218.java:2774) ~[client-intermediary.jar:?]
	at net.minecraft.class_3218.method_18765(class_3218.java:410) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:948) ~[client-intermediary.jar:?]
	... 5 more
	
	seems to happen right when a haunt occurs near the player

**Comment by Yegiyan** [comment]
Thanks, I'll take a look and see what the issue is

**Comment by dopadream** [comment]
Still is crashing. The issue is due to the mod trying to mixin to the GlassBlock class which does not exist on 1.20.3 and onwards. I'm not sure what the replacement class is
