### ISSUE TITLE
Sleeping Haunt not working

### ISSUE THREAD

**Issue by Wash113** [Yegiyan/Him#5]
MC: 1.21
Loader: Fabric 0.15.11, API 0.100.6+1.21
Mod Version: 1.4.1

Hey there! 

Noticed that the sleeping haunt isnt working on my server. The server log throws the following error when the player sleeps after Herobrine decides to haunt a sleeping player. Happy Hunting!

[00:00:33] [Server thread/INFO]: Herobrine will haunt a sleeping player tonight!
[00:08:22] [Server thread/INFO]: Herobrine stalking from class_2338{x=-7552, y=112, z=1803}
[00:08:37] [pool-14-thread-1/INFO]: [STDERR]: java.util.ConcurrentModificationException: Async entity load
[00:08:37] [pool-14-thread-1/INFO]: [STDERR]:     at net.minecraft.class_3898.handler$zgh000$c2me-fixes-general-threading-issues$preventAsyncEntityLoad(class_3898.java:4792)
[00:08:37] [pool-14-thread-1/INFO]: [STDERR]:     at net.minecraft.class_3898.method_18701(class_3898.java)
[00:08:37] [pool-14-thread-1/INFO]: [STDERR]:     at net.minecraft.class_3215.method_18755(class_3215.java:467)
[00:08:37] [pool-14-thread-1/INFO]: [STDERR]:     at net.minecraft.class_3218$class_5526.method_31436(class_3218.java:1592)
[00:08:37] [pool-14-thread-1/INFO]: [STDERR]:     at net.minecraft.class_3218$class_5526.method_31798(class_3218.java:1570)
[00:08:37] [pool-14-thread-1/INFO]: [STDERR]:     at net.minecraft.class_5579.method_31847(class_5579.java:216)
[00:08:37] [pool-14-thread-1/INFO]: [STDERR]:     at net.minecraft.class_5579.method_31820(class_5579.java:186)
[00:08:37] [pool-14-thread-1/INFO]: [STDERR]:     at net.minecraft.class_5579.method_31818(class_5579.java:167)
[00:08:37] [pool-14-thread-1/INFO]: [STDERR]:     at net.minecraft.class_3218.method_14175(class_3218.java:935)
[00:08:37] [pool-14-thread-1/INFO]: [STDERR]:     at net.minecraft.class_3218.method_8649(class_3218.java:893)
[00:08:37] [pool-14-thread-1/INFO]: [STDERR]:     at com.him.events.Haunt.lambda$isPlayerSleeping$1(Haunt.java:92)
[00:08:37] [pool-14-thread-1/INFO]: [STDERR]:     at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[00:08:37] [pool-14-thread-1/INFO]: [STDERR]:     at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
[00:08:37] [pool-14-thread-1/INFO]: [STDERR]:     at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
[00:08:37] [pool-14-thread-1/INFO]: [STDERR]:     at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[00:08:37] [pool-14-thread-1/INFO]: [STDERR]:     at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[00:08:37] [pool-14-thread-1/INFO]: [STDERR]:     at java.base/java.lang.Thread.run(Unknown Source)

**Comment by Yegiyan** [comment]
Thanks for the report! I’ll get it fixed either tomorrow or the next day.

**Comment by Wash113** [comment]
Sounds great, thanks @Yegiyan !

**Comment by Yegiyan** [comment]
Issue should be resolved now, make sure everyone on the server updates to v1.5.0

**Comment by Wash113** [comment]
Will do, thanks again @Yegiyan !
